// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.
import * as $0 from "./routes/171717.tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/about.tsx";
import * as $5 from "./routes/ai.tsx";
import * as $6 from "./routes/aiok.tsx";
import * as $7 from "./routes/card.tsx";
import * as $8 from "./routes/card_version.tsx";
import * as $9 from "./routes/custom.tsx";
import * as $10 from "./routes/greet/[name].tsx";
import * as $11 from "./routes/index.tsx";
import * as $12 from "./routes/join.tsx";
import * as $13 from "./routes/member.tsx";
import * as $14 from "./routes/position.tsx";
import * as $15 from "./routes/positions.tsx";
import * as $16 from "./routes/register.tsx";
import * as $17 from "./routes/unopen.tsx";
import * as $18 from "./routes/verify.ts";
import * as $19 from "./routes/api/send-remind.ts";
import * as $$0 from "./islands/position-list.tsx";

const manifest = {
  routes: {
    "./routes/171717.tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/about.tsx": $4,
    "./routes/ai.tsx": $5,
    "./routes/aiok.tsx": $6,
    "./routes/card.tsx": $7,
    "./routes/card_version.tsx": $8,
    "./routes/custom.tsx": $9,
    "./routes/greet/[name].tsx": $10,
    "./routes/index.tsx": $11,
    "./routes/join.tsx": $12,
    "./routes/member.tsx": $13,
    "./routes/position.tsx": $14,
    "./routes/positions.tsx": $15,
    "./routes/register.tsx": $16,
    "./routes/unopen.tsx": $17,
    "./routes/verify.ts": $18,
    "./routes/api/send-remind.ts": $19,
  },
  islands: {
    "./islands/position-list.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
